language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng build --prod --base-href https://jump4fun.github.io/Website4Fun/
- mv dist/website4fun/index.html dist/website4fun/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/website4fun
  on:
    branch: master